/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components.Pages;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.HashMap;
import Database.Database;
import java.awt.Dimension;
import java.text.DecimalFormat;
import java.util.*;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Admin extends javax.swing.JPanel {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
//        setLayout(new java.awt.BorderLayout());
        this.setPreferredSize(new Dimension(1050, 720));

        populateTableWithAccounts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new raven.crazypanel.CrazyPanel();
        ScrollPane = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TabPanel = new raven.crazypanel.CrazyPanel();
        AddButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        SearchBar = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        MainPanel.setBackground(new java.awt.Color(51, 255, 51));
        MainPanel.setLayout(null);

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 76, 172)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Name", "Rank", "User_name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollPane.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        MainPanel.add(ScrollPane);
        ScrollPane.setBounds(20, 140, 980, 406);

        TabPanel.setBackground(new java.awt.Color(255, 255, 255));
        TabPanel.setPreferredSize(new java.awt.Dimension(1019, 34));
        TabPanel.setLayout(null);

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        TabPanel.add(AddButton);
        AddButton.setBounds(680, 10, 90, 28);

        UpdateButton.setText("Update");
        UpdateButton.setMaximumSize(new java.awt.Dimension(49, 28));
        UpdateButton.setMinimumSize(new java.awt.Dimension(49, 28));
        UpdateButton.setName(""); // NOI18N
        UpdateButton.setPreferredSize(new java.awt.Dimension(49, 28));
        TabPanel.add(UpdateButton);
        UpdateButton.setBounds(780, 10, 90, 28);

        DeleteButton.setText("Delete");
        DeleteButton.setMaximumSize(new java.awt.Dimension(49, 28));
        DeleteButton.setMinimumSize(new java.awt.Dimension(49, 28));
        DeleteButton.setName(""); // NOI18N
        DeleteButton.setPreferredSize(new java.awt.Dimension(49, 28));
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        TabPanel.add(DeleteButton);
        DeleteButton.setBounds(880, 10, 90, 28);

        SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarActionPerformed(evt);
            }
        });
        TabPanel.add(SearchBar);
        SearchBar.setBounds(0, 10, 170, 28);

        MainPanel.add(TabPanel);
        TabPanel.setBounds(20, 90, 980, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBarActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int rowCount = model.getRowCount();
        List<Integer> rowsToDelete = new ArrayList<>();
        StringBuilder selectedUsers = new StringBuilder();

        // fnd all checked rows
        for (int i = 0; i < rowCount; i++) {
            Boolean isChecked = (Boolean) model.getValueAt(i, 0);
            if (isChecked != null && isChecked) {
                rowsToDelete.add(i);
                selectedUsers.append("- ").append(model.getValueAt(i, 1)).append("\n");
            }
        }

        if (rowsToDelete.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No user selected for deletion.");
            return;
        }

        //wraning dialog
        int response = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete the following users?\n\n" + selectedUsers,
                "Confirm Deletion",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        //delete users after confirmed
        if (response == javax.swing.JOptionPane.YES_OPTION) {
            for (int i = rowsToDelete.size() - 1; i >= 0; i--) {
                int rowIndex = rowsToDelete.get(i);
                String userName = (String) model.getValueAt(rowIndex, 3);  // getusername from the row

                //deletes the selected user from the database method
                removeUserFromDatabase(userName);

                model.removeRow(rowIndex); //remove the row from the table
            }
            System.out.println("Deleted users:\n" + selectedUsers);
        } else {
            System.out.println("Deletion cancelled.");
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        addNewUser();
    }//GEN-LAST:event_AddButtonActionPerformed

    private void addUserToDatabase(String fullName, String userName, String userPassword, String rank, String permissions) {
        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/schedule_manager_db", "root", "")) {
            if (permissions == null || permissions.isEmpty()) {
                permissions = "user";

            }

            String insertQuery = "INSERT INTO accounts (user_name, user_password, full_name, rank, permissions) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement statement = connection.prepareStatement(insertQuery);
            statement.setString(1, userName);
            statement.setString(2, userPassword);
            statement.setString(3, fullName);
            statement.setString(4, rank);
            statement.setString(5, permissions);
            statement.executeUpdate();

            System.out.println("User " + userName + " added to database.");
        } catch (SQLException e) {
            System.out.println("Error adding user to database: " + e.getMessage());
        }
    }

    private void addNewUser() {
        //dialog
        javax.swing.JDialog dialog = new javax.swing.JDialog();
        dialog.setTitle("Add New User");
        dialog.setSize(300, 250);
        dialog.setLayout(new java.awt.GridLayout(5, 2));

        //new labels and text fields
        javax.swing.JLabel fullNameLabel = new javax.swing.JLabel("Full Name:");
        javax.swing.JTextField fullNameField = new javax.swing.JTextField();
        javax.swing.JLabel userNameLabel = new javax.swing.JLabel("Username:");
        javax.swing.JTextField userNameField = new javax.swing.JTextField();
        javax.swing.JLabel passwordLabel = new javax.swing.JLabel("Password:");
        javax.swing.JPasswordField passwordField = new javax.swing.JPasswordField();
        javax.swing.JLabel rankLabel = new javax.swing.JLabel("Rank:");
        javax.swing.JTextField rankField = new javax.swing.JTextField();

        //buttons
        javax.swing.JButton submitButton = new javax.swing.JButton("Submit");
        javax.swing.JButton cancelButton = new javax.swing.JButton("Cancel");

        //adds to dialog
        dialog.add(fullNameLabel);
        dialog.add(fullNameField);
        dialog.add(userNameLabel);
        dialog.add(userNameField);
        dialog.add(passwordLabel);
        dialog.add(passwordField);
        dialog.add(rankLabel);
        dialog.add(rankField);
        dialog.add(submitButton);
        dialog.add(cancelButton);

        dialog.setLocationRelativeTo(null);
        //dialog pops
        dialog.setVisible(true);

        //submit buutton
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

                String fullName = fullNameField.getText();
                String userName = userNameField.getText();
                String userPassword = new String(passwordField.getPassword());
                String rank = rankField.getText();

                //checks for validationn
                if (fullName.isEmpty() || userName.isEmpty() || userPassword.isEmpty() || rank.isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(dialog, "All fields are required!");
                    return;
                }

                if (Pattern.compile("\\d+").matcher(fullName).find()) {
                    javax.swing.JOptionPane.showMessageDialog(dialog, "Bugo way name nga naay number!");
                    return;
                }

                //adding to database
                addUserToDatabase(fullName, userName, userPassword, rank, "Basic");

                dialog.dispose();

                //udpdates table with the new user that is added
                Database.initDatabase();
                populateTableWithAccounts();
            }
        });

        //cancel button
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog.dispose();
            }
        });
    }

    private void populateTableWithAccounts() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        // Populate table with accounts from the database
        for (HashMap<String, String> user : Database.getAccounts()) {
            model.addRow(new Object[]{
                false,
                user.get("full_name"),
                user.get("rank"),
                user.get("user_name")
            });
        }
    }

    private void removeUserFromDatabase(String userName) {
        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/schedule_manager_db", "root", "")) {
            String deleteQuery = "DELETE FROM accounts WHERE user_name = ?";
            PreparedStatement statement = connection.prepareStatement(deleteQuery);
            statement.setString(1, userName);
            statement.executeUpdate();

            // get data after deletion
            Database.initDatabase();
            populateTableWithAccounts(); // new table wis updated data

            System.out.println("User " + userName + " deleted from database.");
        } catch (SQLException e) {
            System.out.println("Error deleting user from database: " + e.getMessage());
        }
    }

    private double getAmount(int from, int to) {
        Random ran = new Random();
        return (ran.nextInt(to - from) + from) * ran.nextDouble();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton DeleteButton;
    private raven.crazypanel.CrazyPanel MainPanel;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTextField SearchBar;
    private raven.crazypanel.CrazyPanel TabPanel;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
