/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components.Pages;

import static Database.Database.dbAccounts;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public final class ScheduleCreator extends javax.swing.JPanel {

    /**
     * Creates new form ScheduleCreator
     */
    public ScheduleCreator() {
        System.out.println("Initialized Schedule Creator");
        initComponents();
        this.setPreferredSize(new Dimension(1050, 720));
        getSchedule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TimeRow = new Components.Cell.Cell();
        Monday = new Components.Cell.Cell();
        Tuesday = new Components.Cell.Cell();
        Wednesday = new Components.Cell.Cell();
        Thursday = new Components.Cell.Cell();
        Friday = new Components.Cell.Cell();
        Saturday = new Components.Cell.Cell();
        TimeFrame1 = new Components.Cell.Cell();
        TimeCellRow1_1 = new Components.Cell.Cell();
        TimeCellRow2_1 = new Components.Cell.Cell();
        TimeCellRow3_1 = new Components.Cell.Cell();
        TimeCellRow4_1 = new Components.Cell.Cell();
        TimeCellRow5_1 = new Components.Cell.Cell();
        TimeCellRow6_1 = new Components.Cell.Cell();
        TimeFrame2 = new Components.Cell.Cell();
        TimeCellRow1_2 = new Components.Cell.Cell();
        TimeCellRow2_2 = new Components.Cell.Cell();
        TimeCellRow3_2 = new Components.Cell.Cell();
        TimeCellRow4_2 = new Components.Cell.Cell();
        TimeCellRow5_2 = new Components.Cell.Cell();
        TimeCellRow6_2 = new Components.Cell.Cell();
        TimeFrame3 = new Components.Cell.Cell();
        TimeCellRow1_3 = new Components.Cell.Cell();
        TimeCellRow2_3 = new Components.Cell.Cell();
        TimeCellRow3_3 = new Components.Cell.Cell();
        TimeCellRow4_3 = new Components.Cell.Cell();
        TimeCellRow5_3 = new Components.Cell.Cell();
        TimeCellRow6_3 = new Components.Cell.Cell();
        TimeFrame4 = new Components.Cell.Cell();
        TimeCellRow1_4 = new Components.Cell.Cell();
        TimeCellRow2_4 = new Components.Cell.Cell();
        TimeCellRow3_4 = new Components.Cell.Cell();
        TimeCellRow4_4 = new Components.Cell.Cell();
        TimeCellRow5_4 = new Components.Cell.Cell();
        TimeCellRow6_4 = new Components.Cell.Cell();
        TimeFrame5 = new Components.Cell.Cell();
        TimeCellRow1_5 = new Components.Cell.Cell();
        TimeCellRow2_5 = new Components.Cell.Cell();
        TimeCellRow3_5 = new Components.Cell.Cell();
        TimeCellRow4_5 = new Components.Cell.Cell();
        TimeCellRow5_5 = new Components.Cell.Cell();
        TimeCellRow6_5 = new Components.Cell.Cell();
        TimeFrame6 = new Components.Cell.Cell();
        TimeCellRow1_6 = new Components.Cell.Cell();
        TimeCellRow2_6 = new Components.Cell.Cell();
        TimeCellRow3_6 = new Components.Cell.Cell();
        TimeCellRow4_6 = new Components.Cell.Cell();
        TimeCellRow5_6 = new Components.Cell.Cell();
        TimeCellRow6_6 = new Components.Cell.Cell();
        TimeFrame7 = new Components.Cell.Cell();
        TimeCellRow1_7 = new Components.Cell.Cell();
        TimeCellRow2_7 = new Components.Cell.Cell();
        TimeCellRow3_7 = new Components.Cell.Cell();
        TimeCellRow4_7 = new Components.Cell.Cell();
        TimeCellRow5_7 = new Components.Cell.Cell();
        TimeCellRow6_7 = new Components.Cell.Cell();
        TimeFrame8 = new Components.Cell.Cell();
        TimeCellRow1_8 = new Components.Cell.Cell();
        TimeCellRow2_8 = new Components.Cell.Cell();
        TimeCellRow3_8 = new Components.Cell.Cell();
        TimeCellRow4_8 = new Components.Cell.Cell();
        TimeCellRow5_8 = new Components.Cell.Cell();
        TimeCellRow6_8 = new Components.Cell.Cell();
        TimeFrame9 = new Components.Cell.Cell();
        TimeCellRow1_9 = new Components.Cell.Cell();
        TimeCellRow2_9 = new Components.Cell.Cell();
        TimeCellRow3_9 = new Components.Cell.Cell();
        TimeCellRow4_9 = new Components.Cell.Cell();
        TimeCellRow5_9 = new Components.Cell.Cell();
        TimeCellRow6_9 = new Components.Cell.Cell();
        TimeFrame10 = new Components.Cell.Cell();
        TimeCellRow1_10 = new Components.Cell.Cell();
        TimeCellRow2_10 = new Components.Cell.Cell();
        TimeCellRow3_10 = new Components.Cell.Cell();
        TimeCellRow4_10 = new Components.Cell.Cell();
        TimeCellRow5_10 = new Components.Cell.Cell();
        TimeCellRow6_10 = new Components.Cell.Cell();
        TimeFrame11 = new Components.Cell.Cell();
        TimeCellRow1_11 = new Components.Cell.Cell();
        TimeCellRow2_11 = new Components.Cell.Cell();
        TimeCellRow3_11 = new Components.Cell.Cell();
        TimeCellRow4_11 = new Components.Cell.Cell();
        TimeCellRow5_11 = new Components.Cell.Cell();
        TimeCellRow6_11 = new Components.Cell.Cell();
        TimeFrame12 = new Components.Cell.Cell();
        TimeCellRow1_12 = new Components.Cell.Cell();
        TimeCellRow2_12 = new Components.Cell.Cell();
        TimeCellRow3_12 = new Components.Cell.Cell();
        TimeCellRow4_12 = new Components.Cell.Cell();
        TimeCellRow5_12 = new Components.Cell.Cell();
        TimeCellRow6_12 = new Components.Cell.Cell();
        TimeFrame13 = new Components.Cell.Cell();
        TimeCellRow1_13 = new Components.Cell.Cell();
        TimeCellRow2_13 = new Components.Cell.Cell();
        TimeCellRow3_13 = new Components.Cell.Cell();
        TimeCellRow4_13 = new Components.Cell.Cell();
        TimeCellRow5_13 = new Components.Cell.Cell();
        TimeCellRow6_13 = new Components.Cell.Cell();
        TimeFrame14 = new Components.Cell.Cell();
        TimeCellRow1_14 = new Components.Cell.Cell();
        TimeCellRow2_14 = new Components.Cell.Cell();
        TimeCellRow3_14 = new Components.Cell.Cell();
        TimeCellRow4_14 = new Components.Cell.Cell();
        TimeCellRow5_14 = new Components.Cell.Cell();
        TimeCellRow6_14 = new Components.Cell.Cell();
        TimeFrame15 = new Components.Cell.Cell();
        TimeCellRow1_15 = new Components.Cell.Cell();
        TimeCellRow2_15 = new Components.Cell.Cell();
        TimeCellRow3_15 = new Components.Cell.Cell();
        TimeCellRow4_15 = new Components.Cell.Cell();
        TimeCellRow5_15 = new Components.Cell.Cell();
        TimeCellRow6_15 = new Components.Cell.Cell();
        TimeFrame16 = new Components.Cell.Cell();
        TimeCellRow1_16 = new Components.Cell.Cell();
        TimeCellRow2_16 = new Components.Cell.Cell();
        TimeCellRow3_16 = new Components.Cell.Cell();
        TimeCellRow4_16 = new Components.Cell.Cell();
        TimeCellRow5_16 = new Components.Cell.Cell();
        TimeCellRow6_16 = new Components.Cell.Cell();
        TimeFrame17 = new Components.Cell.Cell();
        TimeCellRow1_17 = new Components.Cell.Cell();
        TimeCellRow2_17 = new Components.Cell.Cell();
        TimeCellRow3_17 = new Components.Cell.Cell();
        TimeCellRow4_17 = new Components.Cell.Cell();
        TimeCellRow5_17 = new Components.Cell.Cell();
        TimeCellRow6_17 = new Components.Cell.Cell();
        TimeFrame18 = new Components.Cell.Cell();
        TimeCellRow1_18 = new Components.Cell.Cell();
        TimeCellRow2_18 = new Components.Cell.Cell();
        TimeCellRow3_18 = new Components.Cell.Cell();
        TimeCellRow4_18 = new Components.Cell.Cell();
        TimeCellRow5_18 = new Components.Cell.Cell();
        TimeCellRow6_18 = new Components.Cell.Cell();
        TimeFrame19 = new Components.Cell.Cell();
        TimeCellRow1_19 = new Components.Cell.Cell();
        TimeCellRow2_19 = new Components.Cell.Cell();
        TimeCellRow3_19 = new Components.Cell.Cell();
        TimeCellRow4_19 = new Components.Cell.Cell();
        TimeCellRow5_19 = new Components.Cell.Cell();
        TimeCellRow6_19 = new Components.Cell.Cell();
        TimeFrame20 = new Components.Cell.Cell();
        TimeCellRow1_20 = new Components.Cell.Cell();
        TimeCellRow2_20 = new Components.Cell.Cell();
        TimeCellRow3_20 = new Components.Cell.Cell();
        TimeCellRow4_20 = new Components.Cell.Cell();
        TimeCellRow5_20 = new Components.Cell.Cell();
        TimeCellRow6_20 = new Components.Cell.Cell();
        TimeFrame21 = new Components.Cell.Cell();
        TimeCellRow1_21 = new Components.Cell.Cell();
        TimeCellRow2_21 = new Components.Cell.Cell();
        TimeCellRow3_21 = new Components.Cell.Cell();
        TimeCellRow4_21 = new Components.Cell.Cell();
        TimeCellRow5_21 = new Components.Cell.Cell();
        TimeCellRow6_21 = new Components.Cell.Cell();
        TimeFrame22 = new Components.Cell.Cell();
        TimeCellRow1_22 = new Components.Cell.Cell();
        TimeCellRow2_22 = new Components.Cell.Cell();
        TimeCellRow3_22 = new Components.Cell.Cell();
        TimeCellRow4_22 = new Components.Cell.Cell();
        TimeCellRow5_22 = new Components.Cell.Cell();
        TimeCellRow6_22 = new Components.Cell.Cell();
        TimeFrame23 = new Components.Cell.Cell();
        TimeCellRow1_23 = new Components.Cell.Cell();
        TimeCellRow2_23 = new Components.Cell.Cell();
        TimeCellRow3_23 = new Components.Cell.Cell();
        TimeCellRow4_23 = new Components.Cell.Cell();
        TimeCellRow5_23 = new Components.Cell.Cell();
        TimeCellRow6_23 = new Components.Cell.Cell();
        TimeFrame24 = new Components.Cell.Cell();
        TimeCellRow1_24 = new Components.Cell.Cell();
        TimeCellRow2_24 = new Components.Cell.Cell();
        TimeCellRow3_24 = new Components.Cell.Cell();
        TimeCellRow4_24 = new Components.Cell.Cell();
        TimeCellRow5_24 = new Components.Cell.Cell();
        TimeCellRow6_24 = new Components.Cell.Cell();
        TimeFrame25 = new Components.Cell.Cell();
        TimeCellRow1_25 = new Components.Cell.Cell();
        TimeCellRow2_25 = new Components.Cell.Cell();
        TimeCellRow3_25 = new Components.Cell.Cell();
        TimeCellRow4_25 = new Components.Cell.Cell();
        TimeCellRow5_25 = new Components.Cell.Cell();
        TimeCellRow6_25 = new Components.Cell.Cell();

        setLayout(new java.awt.GridLayout(26, 7));

        TimeRow.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeRow);

        Monday.setBorder(new javax.swing.border.MatteBorder(null));
        Monday.setText("Monday");
        add(Monday);

        Tuesday.setBorder(new javax.swing.border.MatteBorder(null));
        Tuesday.setText("Tuesday");
        add(Tuesday);

        Wednesday.setBorder(new javax.swing.border.MatteBorder(null));
        Wednesday.setText("Wednesday");
        add(Wednesday);

        Thursday.setBorder(new javax.swing.border.MatteBorder(null));
        Thursday.setText("Thursday");
        add(Thursday);

        Friday.setBorder(new javax.swing.border.MatteBorder(null));
        Friday.setText("Friday");
        add(Friday);

        Saturday.setBorder(new javax.swing.border.MatteBorder(null));
        Saturday.setText("Saturday");
        add(Saturday);

        TimeFrame1.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame1.setText("07:30 - 08:00");
        TimeFrame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeFrame1ActionPerformed(evt);
            }
        });
        add(TimeFrame1);

        TimeCellRow1_1.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_1);

        TimeCellRow2_1.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_1);

        TimeCellRow3_1.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_1);

        TimeCellRow4_1.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_1);

        TimeCellRow5_1.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_1);

        TimeCellRow6_1.setBorder(new javax.swing.border.MatteBorder(null));
        TimeCellRow6_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeCellRow6_1ActionPerformed(evt);
            }
        });
        add(TimeCellRow6_1);

        TimeFrame2.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame2.setText("08:00 - 08:30");
        add(TimeFrame2);

        TimeCellRow1_2.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_2);

        TimeCellRow2_2.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_2);

        TimeCellRow3_2.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_2);

        TimeCellRow4_2.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_2);

        TimeCellRow5_2.setBorder(new javax.swing.border.MatteBorder(null));
        TimeCellRow5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeCellRow5_2ActionPerformed(evt);
            }
        });
        add(TimeCellRow5_2);

        TimeCellRow6_2.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_2);

        TimeFrame3.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame3.setText("08:30 - 09:00");
        add(TimeFrame3);

        TimeCellRow1_3.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_3);

        TimeCellRow2_3.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_3);

        TimeCellRow3_3.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_3);

        TimeCellRow4_3.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_3);

        TimeCellRow5_3.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_3);

        TimeCellRow6_3.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_3);

        TimeFrame4.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame4.setText("09:00 - 09:30");
        add(TimeFrame4);

        TimeCellRow1_4.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_4);

        TimeCellRow2_4.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_4);

        TimeCellRow3_4.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_4);

        TimeCellRow4_4.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_4);

        TimeCellRow5_4.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_4);

        TimeCellRow6_4.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_4);

        TimeFrame5.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame5.setText("09:30 - 10:00");
        add(TimeFrame5);

        TimeCellRow1_5.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_5);

        TimeCellRow2_5.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_5);

        TimeCellRow3_5.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_5);

        TimeCellRow4_5.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_5);

        TimeCellRow5_5.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_5);

        TimeCellRow6_5.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_5);

        TimeFrame6.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame6.setText("10:00- 10:30");
        add(TimeFrame6);

        TimeCellRow1_6.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_6);

        TimeCellRow2_6.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_6);

        TimeCellRow3_6.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_6);

        TimeCellRow4_6.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_6);

        TimeCellRow5_6.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_6);

        TimeCellRow6_6.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_6);

        TimeFrame7.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame7.setText("10:30 - 11:00");
        add(TimeFrame7);

        TimeCellRow1_7.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_7);

        TimeCellRow2_7.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_7);

        TimeCellRow3_7.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_7);

        TimeCellRow4_7.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_7);

        TimeCellRow5_7.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_7);

        TimeCellRow6_7.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_7);

        TimeFrame8.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame8.setText("11:00 - 11:30");
        add(TimeFrame8);

        TimeCellRow1_8.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_8);

        TimeCellRow2_8.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_8);

        TimeCellRow3_8.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_8);

        TimeCellRow4_8.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_8);

        TimeCellRow5_8.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_8);

        TimeCellRow6_8.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_8);

        TimeFrame9.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame9.setText("11:30 - 12:00");
        add(TimeFrame9);

        TimeCellRow1_9.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_9);

        TimeCellRow2_9.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_9);

        TimeCellRow3_9.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_9);

        TimeCellRow4_9.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_9);

        TimeCellRow5_9.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_9);

        TimeCellRow6_9.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_9);

        TimeFrame10.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame10.setText("12:00 - 12:30");
        add(TimeFrame10);

        TimeCellRow1_10.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_10);

        TimeCellRow2_10.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_10);

        TimeCellRow3_10.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_10);

        TimeCellRow4_10.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_10);

        TimeCellRow5_10.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_10);

        TimeCellRow6_10.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_10);

        TimeFrame11.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame11.setText("12:30 - 1:00");
        add(TimeFrame11);

        TimeCellRow1_11.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_11);

        TimeCellRow2_11.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_11);

        TimeCellRow3_11.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_11);

        TimeCellRow4_11.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_11);

        TimeCellRow5_11.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_11);

        TimeCellRow6_11.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_11);

        TimeFrame12.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame12.setText("1:00 - 1:30");
        add(TimeFrame12);

        TimeCellRow1_12.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_12);

        TimeCellRow2_12.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_12);

        TimeCellRow3_12.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_12);

        TimeCellRow4_12.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_12);

        TimeCellRow5_12.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_12);

        TimeCellRow6_12.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_12);

        TimeFrame13.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame13.setText("1:30 - 2:00");
        add(TimeFrame13);

        TimeCellRow1_13.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_13);

        TimeCellRow2_13.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_13);

        TimeCellRow3_13.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_13);

        TimeCellRow4_13.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_13);

        TimeCellRow5_13.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_13);

        TimeCellRow6_13.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_13);

        TimeFrame14.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame14.setText("2:00 - 2:30");
        add(TimeFrame14);

        TimeCellRow1_14.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_14);

        TimeCellRow2_14.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_14);

        TimeCellRow3_14.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_14);

        TimeCellRow4_14.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_14);

        TimeCellRow5_14.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_14);

        TimeCellRow6_14.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_14);

        TimeFrame15.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame15.setText("2:30 - 3:00");
        add(TimeFrame15);

        TimeCellRow1_15.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_15);

        TimeCellRow2_15.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_15);

        TimeCellRow3_15.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_15);

        TimeCellRow4_15.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_15);

        TimeCellRow5_15.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_15);

        TimeCellRow6_15.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_15);

        TimeFrame16.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame16.setText("3:00 - 3:30");
        add(TimeFrame16);

        TimeCellRow1_16.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_16);

        TimeCellRow2_16.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_16);

        TimeCellRow3_16.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_16);

        TimeCellRow4_16.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_16);

        TimeCellRow5_16.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_16);

        TimeCellRow6_16.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_16);

        TimeFrame17.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame17.setText("3:30 - 4:00");
        add(TimeFrame17);

        TimeCellRow1_17.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_17);

        TimeCellRow2_17.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_17);

        TimeCellRow3_17.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_17);

        TimeCellRow4_17.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_17);

        TimeCellRow5_17.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_17);

        TimeCellRow6_17.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_17);

        TimeFrame18.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame18.setText("4:00 - 4:30");
        add(TimeFrame18);

        TimeCellRow1_18.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_18);

        TimeCellRow2_18.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_18);

        TimeCellRow3_18.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_18);

        TimeCellRow4_18.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_18);

        TimeCellRow5_18.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_18);

        TimeCellRow6_18.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_18);

        TimeFrame19.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame19.setText("4:30 - 5:00");
        add(TimeFrame19);

        TimeCellRow1_19.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_19);

        TimeCellRow2_19.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_19);

        TimeCellRow3_19.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_19);

        TimeCellRow4_19.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_19);

        TimeCellRow5_19.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_19);

        TimeCellRow6_19.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_19);

        TimeFrame20.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame20.setText("5:00 - 5:30");
        add(TimeFrame20);

        TimeCellRow1_20.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_20);

        TimeCellRow2_20.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_20);

        TimeCellRow3_20.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_20);

        TimeCellRow4_20.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_20);

        TimeCellRow5_20.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_20);

        TimeCellRow6_20.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_20);

        TimeFrame21.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame21.setText("5:30 - 6:00");
        add(TimeFrame21);

        TimeCellRow1_21.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_21);

        TimeCellRow2_21.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_21);

        TimeCellRow3_21.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_21);

        TimeCellRow4_21.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_21);

        TimeCellRow5_21.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_21);

        TimeCellRow6_21.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_21);

        TimeFrame22.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame22.setText("6:00 - 6:30");
        add(TimeFrame22);

        TimeCellRow1_22.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_22);

        TimeCellRow2_22.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_22);

        TimeCellRow3_22.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_22);

        TimeCellRow4_22.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_22);

        TimeCellRow5_22.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_22);

        TimeCellRow6_22.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_22);

        TimeFrame23.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame23.setText("6:30 - 7:00");
        add(TimeFrame23);

        TimeCellRow1_23.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_23);

        TimeCellRow2_23.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_23);

        TimeCellRow3_23.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_23);

        TimeCellRow4_23.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_23);

        TimeCellRow5_23.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_23);

        TimeCellRow6_23.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_23);

        TimeFrame24.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame24.setText("7:00 - 7:30");
        add(TimeFrame24);

        TimeCellRow1_24.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_24);

        TimeCellRow2_24.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_24);

        TimeCellRow3_24.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_24);

        TimeCellRow4_24.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_24);

        TimeCellRow5_24.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_24);

        TimeCellRow6_24.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_24);

        TimeFrame25.setBorder(new javax.swing.border.MatteBorder(null));
        TimeFrame25.setText("7:30 - 8:00");
        add(TimeFrame25);

        TimeCellRow1_25.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow1_25);

        TimeCellRow2_25.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow2_25);

        TimeCellRow3_25.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow3_25);

        TimeCellRow4_25.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow4_25);

        TimeCellRow5_25.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow5_25);

        TimeCellRow6_25.setBorder(new javax.swing.border.MatteBorder(null));
        add(TimeCellRow6_25);
    }// </editor-fold>//GEN-END:initComponents

    private void TimeFrame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeFrame1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeFrame1ActionPerformed

    private void TimeCellRow6_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeCellRow6_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeCellRow6_1ActionPerformed

    private void TimeCellRow5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeCellRow5_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeCellRow5_2ActionPerformed
    
    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection("jdbc:mysql://localhost:3306/schedule_manager_db", "root", "");
    }

    public void getSchedule() {
        System.out.println("Getting Schedule From Database...");
        try (Connection connection = getConnection()) {
          
            Statement statement = connection.createStatement();
            ResultSet schedulesRetval = statement.executeQuery("SELECT * FROM schedule");


            while (schedulesRetval.next()) {
                String sRoom = schedulesRetval.getString("room_id");
                String sTime = schedulesRetval.getString("time");
                String sEmployeeId = schedulesRetval.getString("employee_id");
                String sDay = schedulesRetval.getString("day");
                System.out.println(sRoom + " | " + sTime + " | " + sEmployeeId +  " | " + sDay);
            }

           
            System.out.println("Database fetched schedules successfully!");
        } catch (SQLException e) {
            System.out.println("Error " + e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.Cell.Cell Friday;
    private Components.Cell.Cell Monday;
    private Components.Cell.Cell Saturday;
    private Components.Cell.Cell Thursday;
    private Components.Cell.Cell TimeCellRow1_1;
    private Components.Cell.Cell TimeCellRow1_10;
    private Components.Cell.Cell TimeCellRow1_11;
    private Components.Cell.Cell TimeCellRow1_12;
    private Components.Cell.Cell TimeCellRow1_13;
    private Components.Cell.Cell TimeCellRow1_14;
    private Components.Cell.Cell TimeCellRow1_15;
    private Components.Cell.Cell TimeCellRow1_16;
    private Components.Cell.Cell TimeCellRow1_17;
    private Components.Cell.Cell TimeCellRow1_18;
    private Components.Cell.Cell TimeCellRow1_19;
    private Components.Cell.Cell TimeCellRow1_2;
    private Components.Cell.Cell TimeCellRow1_20;
    private Components.Cell.Cell TimeCellRow1_21;
    private Components.Cell.Cell TimeCellRow1_22;
    private Components.Cell.Cell TimeCellRow1_23;
    private Components.Cell.Cell TimeCellRow1_24;
    private Components.Cell.Cell TimeCellRow1_25;
    private Components.Cell.Cell TimeCellRow1_3;
    private Components.Cell.Cell TimeCellRow1_4;
    private Components.Cell.Cell TimeCellRow1_5;
    private Components.Cell.Cell TimeCellRow1_6;
    private Components.Cell.Cell TimeCellRow1_7;
    private Components.Cell.Cell TimeCellRow1_8;
    private Components.Cell.Cell TimeCellRow1_9;
    private Components.Cell.Cell TimeCellRow2_1;
    private Components.Cell.Cell TimeCellRow2_10;
    private Components.Cell.Cell TimeCellRow2_11;
    private Components.Cell.Cell TimeCellRow2_12;
    private Components.Cell.Cell TimeCellRow2_13;
    private Components.Cell.Cell TimeCellRow2_14;
    private Components.Cell.Cell TimeCellRow2_15;
    private Components.Cell.Cell TimeCellRow2_16;
    private Components.Cell.Cell TimeCellRow2_17;
    private Components.Cell.Cell TimeCellRow2_18;
    private Components.Cell.Cell TimeCellRow2_19;
    private Components.Cell.Cell TimeCellRow2_2;
    private Components.Cell.Cell TimeCellRow2_20;
    private Components.Cell.Cell TimeCellRow2_21;
    private Components.Cell.Cell TimeCellRow2_22;
    private Components.Cell.Cell TimeCellRow2_23;
    private Components.Cell.Cell TimeCellRow2_24;
    private Components.Cell.Cell TimeCellRow2_25;
    private Components.Cell.Cell TimeCellRow2_3;
    private Components.Cell.Cell TimeCellRow2_4;
    private Components.Cell.Cell TimeCellRow2_5;
    private Components.Cell.Cell TimeCellRow2_6;
    private Components.Cell.Cell TimeCellRow2_7;
    private Components.Cell.Cell TimeCellRow2_8;
    private Components.Cell.Cell TimeCellRow2_9;
    private Components.Cell.Cell TimeCellRow3_1;
    private Components.Cell.Cell TimeCellRow3_10;
    private Components.Cell.Cell TimeCellRow3_11;
    private Components.Cell.Cell TimeCellRow3_12;
    private Components.Cell.Cell TimeCellRow3_13;
    private Components.Cell.Cell TimeCellRow3_14;
    private Components.Cell.Cell TimeCellRow3_15;
    private Components.Cell.Cell TimeCellRow3_16;
    private Components.Cell.Cell TimeCellRow3_17;
    private Components.Cell.Cell TimeCellRow3_18;
    private Components.Cell.Cell TimeCellRow3_19;
    private Components.Cell.Cell TimeCellRow3_2;
    private Components.Cell.Cell TimeCellRow3_20;
    private Components.Cell.Cell TimeCellRow3_21;
    private Components.Cell.Cell TimeCellRow3_22;
    private Components.Cell.Cell TimeCellRow3_23;
    private Components.Cell.Cell TimeCellRow3_24;
    private Components.Cell.Cell TimeCellRow3_25;
    private Components.Cell.Cell TimeCellRow3_3;
    private Components.Cell.Cell TimeCellRow3_4;
    private Components.Cell.Cell TimeCellRow3_5;
    private Components.Cell.Cell TimeCellRow3_6;
    private Components.Cell.Cell TimeCellRow3_7;
    private Components.Cell.Cell TimeCellRow3_8;
    private Components.Cell.Cell TimeCellRow3_9;
    private Components.Cell.Cell TimeCellRow4_1;
    private Components.Cell.Cell TimeCellRow4_10;
    private Components.Cell.Cell TimeCellRow4_11;
    private Components.Cell.Cell TimeCellRow4_12;
    private Components.Cell.Cell TimeCellRow4_13;
    private Components.Cell.Cell TimeCellRow4_14;
    private Components.Cell.Cell TimeCellRow4_15;
    private Components.Cell.Cell TimeCellRow4_16;
    private Components.Cell.Cell TimeCellRow4_17;
    private Components.Cell.Cell TimeCellRow4_18;
    private Components.Cell.Cell TimeCellRow4_19;
    private Components.Cell.Cell TimeCellRow4_2;
    private Components.Cell.Cell TimeCellRow4_20;
    private Components.Cell.Cell TimeCellRow4_21;
    private Components.Cell.Cell TimeCellRow4_22;
    private Components.Cell.Cell TimeCellRow4_23;
    private Components.Cell.Cell TimeCellRow4_24;
    private Components.Cell.Cell TimeCellRow4_25;
    private Components.Cell.Cell TimeCellRow4_3;
    private Components.Cell.Cell TimeCellRow4_4;
    private Components.Cell.Cell TimeCellRow4_5;
    private Components.Cell.Cell TimeCellRow4_6;
    private Components.Cell.Cell TimeCellRow4_7;
    private Components.Cell.Cell TimeCellRow4_8;
    private Components.Cell.Cell TimeCellRow4_9;
    private Components.Cell.Cell TimeCellRow5_1;
    private Components.Cell.Cell TimeCellRow5_10;
    private Components.Cell.Cell TimeCellRow5_11;
    private Components.Cell.Cell TimeCellRow5_12;
    private Components.Cell.Cell TimeCellRow5_13;
    private Components.Cell.Cell TimeCellRow5_14;
    private Components.Cell.Cell TimeCellRow5_15;
    private Components.Cell.Cell TimeCellRow5_16;
    private Components.Cell.Cell TimeCellRow5_17;
    private Components.Cell.Cell TimeCellRow5_18;
    private Components.Cell.Cell TimeCellRow5_19;
    private Components.Cell.Cell TimeCellRow5_2;
    private Components.Cell.Cell TimeCellRow5_20;
    private Components.Cell.Cell TimeCellRow5_21;
    private Components.Cell.Cell TimeCellRow5_22;
    private Components.Cell.Cell TimeCellRow5_23;
    private Components.Cell.Cell TimeCellRow5_24;
    private Components.Cell.Cell TimeCellRow5_25;
    private Components.Cell.Cell TimeCellRow5_3;
    private Components.Cell.Cell TimeCellRow5_4;
    private Components.Cell.Cell TimeCellRow5_5;
    private Components.Cell.Cell TimeCellRow5_6;
    private Components.Cell.Cell TimeCellRow5_7;
    private Components.Cell.Cell TimeCellRow5_8;
    private Components.Cell.Cell TimeCellRow5_9;
    private Components.Cell.Cell TimeCellRow6_1;
    private Components.Cell.Cell TimeCellRow6_10;
    private Components.Cell.Cell TimeCellRow6_11;
    private Components.Cell.Cell TimeCellRow6_12;
    private Components.Cell.Cell TimeCellRow6_13;
    private Components.Cell.Cell TimeCellRow6_14;
    private Components.Cell.Cell TimeCellRow6_15;
    private Components.Cell.Cell TimeCellRow6_16;
    private Components.Cell.Cell TimeCellRow6_17;
    private Components.Cell.Cell TimeCellRow6_18;
    private Components.Cell.Cell TimeCellRow6_19;
    private Components.Cell.Cell TimeCellRow6_2;
    private Components.Cell.Cell TimeCellRow6_20;
    private Components.Cell.Cell TimeCellRow6_21;
    private Components.Cell.Cell TimeCellRow6_22;
    private Components.Cell.Cell TimeCellRow6_23;
    private Components.Cell.Cell TimeCellRow6_24;
    private Components.Cell.Cell TimeCellRow6_25;
    private Components.Cell.Cell TimeCellRow6_3;
    private Components.Cell.Cell TimeCellRow6_4;
    private Components.Cell.Cell TimeCellRow6_5;
    private Components.Cell.Cell TimeCellRow6_6;
    private Components.Cell.Cell TimeCellRow6_7;
    private Components.Cell.Cell TimeCellRow6_8;
    private Components.Cell.Cell TimeCellRow6_9;
    private Components.Cell.Cell TimeFrame1;
    private Components.Cell.Cell TimeFrame10;
    private Components.Cell.Cell TimeFrame11;
    private Components.Cell.Cell TimeFrame12;
    private Components.Cell.Cell TimeFrame13;
    private Components.Cell.Cell TimeFrame14;
    private Components.Cell.Cell TimeFrame15;
    private Components.Cell.Cell TimeFrame16;
    private Components.Cell.Cell TimeFrame17;
    private Components.Cell.Cell TimeFrame18;
    private Components.Cell.Cell TimeFrame19;
    private Components.Cell.Cell TimeFrame2;
    private Components.Cell.Cell TimeFrame20;
    private Components.Cell.Cell TimeFrame21;
    private Components.Cell.Cell TimeFrame22;
    private Components.Cell.Cell TimeFrame23;
    private Components.Cell.Cell TimeFrame24;
    private Components.Cell.Cell TimeFrame25;
    private Components.Cell.Cell TimeFrame3;
    private Components.Cell.Cell TimeFrame4;
    private Components.Cell.Cell TimeFrame5;
    private Components.Cell.Cell TimeFrame6;
    private Components.Cell.Cell TimeFrame7;
    private Components.Cell.Cell TimeFrame8;
    private Components.Cell.Cell TimeFrame9;
    private Components.Cell.Cell TimeRow;
    private Components.Cell.Cell Tuesday;
    private Components.Cell.Cell Wednesday;
    // End of variables declaration//GEN-END:variables
}
